### ISSUE TITLE
Cannot create EventHubsDirectStream in PySpark

### ISSUE THREAD

**Issue by eduardBM** [Azure/azure-event-hubs-spark#282] opened 2018-03-20 18:36 UTC
Bug Report:

- Actual behavior
snip...
```
org.apache.spark.SparkException: Unexpected element type class com.microsoft.azure.eventhubs.impl.EventDataImpl
	at org.apache.spark.api.python.PythonRDD$.org$apache$spark$api$python$PythonRDD$$write$1(PythonRDD.scala:201)
	at org.apache.spark.api.python.PythonRDD$$anonfun$writeIteratorToStream$1.apply(PythonRDD.scala:204)
	at org.apache.spark.api.python.PythonRDD$$anonfun$writeIteratorToStream$1.apply(PythonRDD.scala:204)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.foreach(EventHubsRDD.scala:101)
```
...
- Expected behavior
being able to print the messages
- Spark version
2.3.0 with pyspark3
- spark-eventhubs artifactId and version
com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.0

Full details:
- example code
```
from pyspark.serializers import PairDeserializer, NoOpSerializer
from pyspark.streaming import DStream


def foreach(rdd):
    rdd.foreach(lambda row: print(row))


ssc = ... sparkStreamingContext
# deserializer to convert java dstream to python dstream
ser = PairDeserializer(NoOpSerializer(), NoOpSerializer())

# java interop
jvm = sc._gateway.jvm
ehConf = jvm.org.apache.spark.eventhubs.EventHubsConf(config['ConnectionString'])

# use java to instantiate the EventHub connector
 directStream = jvm.org.apache.spark.eventhubs.EventHubsUtils.createDirectStream(ssc._jssc, ehConf)

# convert java dstream to python
stream = DStream(directStream, ssc, ser)

stream.foreachRDD(lambda rdd: foreach(rdd))
```

- detailed traceback:
```
2018-03-20 20:29:10 ERROR PythonRunner:91 - Python worker exited unexpectedly (crashed)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/Cellar/apache-spark/2.3.0/libexec/python/lib/pyspark.zip/pyspark/worker.py", line 214, in main
    eval_type = read_int(infile)
  File "/usr/local/Cellar/apache-spark/2.3.0/libexec/python/lib/pyspark.zip/pyspark/serializers.py", line 685, in read_int
    raise EOFError
EOFError

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:298)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:438)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:421)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:252)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:939)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:939)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2067)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2067)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Unexpected element type class com.microsoft.azure.eventhubs.impl.EventDataImpl
	at org.apache.spark.api.python.PythonRDD$.org$apache$spark$api$python$PythonRDD$$write$1(PythonRDD.scala:201)
	at org.apache.spark.api.python.PythonRDD$$anonfun$writeIteratorToStream$1.apply(PythonRDD.scala:204)
	at org.apache.spark.api.python.PythonRDD$$anonfun$writeIteratorToStream$1.apply(PythonRDD.scala:204)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.foreach(EventHubsRDD.scala:101)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:204)
	at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:407)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread$$anonfun$run$1.apply(PythonRunner.scala:215)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1988)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:170)
```

**Comment by sabeegrewal** [comment] 2018-03-20 19:06
Hey Eduard! I haven't gotten this stuff up and running yet on Python - I know Structured Streaming should work, but unsure about Spark Streaming so far. With that said, we're going to have to work together on this 👍 

I can say right away that `EventData` is an interface in Java and the underlying implementation is `EventDataImpl`. In the library we return an `JavaRDD[EventData]` and under the hood those `EventData` are really `EventDataImpl`. It seems that discrepancy is the crux of the issue. 

Does that jog any ideas? There should be a way to address this in `PairDeserializer` or through some kind of cast.

**Comment by eduardBM** [comment] 2018-03-20 19:36
Hi, 
Thanks for the quick reply.

Unfortunately StructuredStreaming doesn't implement the foreach sink in python so i can't use that.

I tried playing with the PairSerializer but it seems that somewhere along the chain the serializer is skipped and a default one is used.
I even tried PairSerializer(True, True) <- which should have raised an exception ("Bool object has no attribute load_stream" or something similar) - but it kept working and returned the same error like before.

This is why i thought of asking here.
I will probably raise an issue with pyspark as well about the serializers passed to createDirectStream but i want to first make sure that this is not an issue with the eventhubs connector.

**Comment by sabeegrewal** [comment] 2018-03-22 01:20
Could you try asking in pyspark? The issue could very well be in the connector, but I'm sure their insight could help us along :) 

Please share the link to the question and/or follow-up when you hear back. I'd definitely like to see this issue through with you 👍

**Comment by eduardBM** [comment] 2018-03-22 09:27
https://issues.apache.org/jira/browse/SPARK-23767

**Comment by grobbie** [comment] 2018-03-22 16:36
The problem is that org.apache.spark.api.python.PythonRDD only supports a small number of RDD types, like String, Key-Value, and byte array, but the EventHubsDirectDStream RDDs are typed to "EventData", which is not supported by PythonRDD.  In order for the RDDs that are generated to be usable by python, EventHubsDirectDStream should probably generate Key-Value pair based RDDs rather than EventHubRDD.

See here:
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala#L185

I was able to get something working end to end by adapting the connector library to spit out custom 'StringRDD's instead of EventHubsRDDs, but its fair to say its an ugly solution. What might be a bit better would be to build a dedicated spark streaming Python API for the connector, at least this would not break existing Scala implementations.

I will continue to tinker.

**Comment by sabeegrewal** [comment] 2018-03-22 17:01
@grobbie thanks for the insight - much appreciated! In the `PairDeserializer`, we should be able to serialize the `EventData` to JSON strings, right? `EventData` is a serializable class. 

Very curious to know what your tinkering yields! Thanks for taking the time 👍

**Comment by grobbie** [comment] 2018-03-23 14:54
Hi unfortunately it doesn't get far enough to deserialize the EventData before it blows up. Like I said the PythonRDD implementation only handles a limited number of data types of which implementations of Serializable is not one. One option might be to serialize the EventData instance to a byte array on the Scala side (which appears to be supported by PythonRDD) and then try to deserialize that to an object on the Python side.

I was able to adapt the code so that it deserializes the EventData to JSON String objects (with the payload a base64 encoded string) and create RDDs of that for Python to process with success.

I will now see about converting EventData to a byte array instead. Either way (JSON string or serialized java object as byte array) this would break any current implementations, however that is not necessarily a problem if the changes are on an extra API that is added just for Pyspark.

**Comment by sabeegrewal** [comment] 2018-03-23 16:45
Cool - thanks for the update, again the time and info is much appreciated.

I'm thinking about taking the time to add more PySpark support for Spark Streaming. Structured Streaming is working pretty well except there is no access to `EventHubsConf`, `ConnectionStringBuilder`, and `EventPosition`. It's usable but it's definitely a pain to have the configuration side of it be such a manual process. 

The Event Hubs team is getting ready to launch a Python SDK (it's just going through stress tests right now) which has an `EventData` implementation. Then I would simply have to implement `EventHubsConf`, `EventPosition`, `ConnectionStringBuilder`, and `EventHubsUtils` which doesn't seem like too much of an endeavor.

**Comment by eduardBM** [comment] 2018-04-18 14:35
@sabeegrewal Hi, any news on this ?

Thanks.

**Comment by sabeegrewal** [comment] 2018-05-02 19:35
Hey @eduardBM - sorry for the hold up. I haven't had time to work on the pyspark side of things :\ There're some other core optimizations I'm trying to finalize and release before I'll have more bandwidth. 

In the meantime, I think Structured Streaming is working pretty well - are you able to give that a shot?

**Comment by eduardBM** [comment] 2018-05-03 04:24
Hi,

Structured streaming didn't (doesn't) have all the python functionality that we needed, that's why we pushed for DStream. We managed to get something working with a patch but it's not perfect.

Thanks.

**Comment by sabeegrewal** [comment] 2018-05-03 19:47
Gotcha, just for reference - what functionality is lacking in Structured Streaming?

**Comment by eduardBM** [comment] 2018-05-04 04:11
Most important functionality we miss is the "foreach sink" - https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#using-foreach.

**Comment by mbrancato** [comment] 2018-05-15 23:55
I don't think this is a pyspark issue. I have a similar problem with Scala.

using the sample driver here: https://github.com/Azure/azure-event-hubs-spark/wiki/What's-new-in-the-latest-connector%3F#new-library-1

I get output that looks like:

> com.microsoft.azure.eventhubs.impl.EventDataImpl@7d95a48
> com.microsoft.azure.eventhubs.impl.EventDataImpl@795cc350
> com.microsoft.azure.eventhubs.impl.EventDataImpl@4f0d4c0
> com.microsoft.azure.eventhubs.impl.EventDataImpl@3960edaf
> com.microsoft.azure.eventhubs.impl.EventDataImpl@32f2a2c8
> com.microsoft.azure.eventhubs.impl.EventDataImpl@304aaaef

The bulk of the code that has the issue is here:

```
    val connectionString = ConnectionStringBuilder().setNamespaceName(ehNamespace).setEventHubName(ehName).setSasKeyName(ehSasKeyName).setSasKey(ehSasKey).build
    val ehConf = EventHubsConf(connectionString)
    val ssc = new StreamingContext(sparkConf, Seconds(5))
    val directStream = EventHubsUtils.createDirectStream(ssc, ehConf)

    directStream.foreachRDD { rdd => rdd.take(10).foreach(println) }

    ssc.start()
    ssc.awaitTermination()
```

**Comment by sabeegrewal** [comment] 2018-05-17 22:12
@mbrancato what's wrong with that output? That's exactly what the output looks like when you print an `EventDataImpl` instance. Are you trying to print out the `EventData` body? If so, let's take this to the gitter chat....I'd be happy to help you there! 👍 

This issue is purely due to the fact that we don't support Spark Streaming with PySpark. I don't have a good timeline for when this support would exist yet!

**Comment by eduardBM** [comment] 2018-05-18 04:17
Indeed, that was the output we saw in pyspark, so we had to "patch" the code (see grobbie's comments) to get the eventdata body.

**Comment by sabeegrewal** [comment] 2019-01-14 18:58
I'm going to close this issue out - looks like Structured Streaming is a viable option now. 
https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#using-foreach-and-foreachbatch

**Closed by sabeegrewal** 2019-01-14 18:58 UTC
Labels: feature
