### ISSUE TITLE
requestSeqNo does not match the received sequence number error

### ISSUE THREAD

**Issue by vijayupadya** [Azure/azure-event-hubs-spark#361] opened 2018-07-24 21:37 UTC
We are frequently hitting the below error when reading from the eventhub. We see this on both DataBricks and HDInsights.
Version: azure-eventhubs-spark_2.11-2.3.2

Callstack:

WARN CachedEventHubsReceiver: 51691860 did not match 51690986.Recreating receiver for {"ehName":"rawvsevents","partitionId":2}
...

ERROR Executor: Exception in task 2.1 in stage 81.0 (TID 24586)
java.lang.AssertionError: assertion failed: requestSeqNo 51691860 does not match the received sequence number 51690986
	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:123)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:157)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.next(EventHubsRDD.scala:147)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.next(EventHubsRDD.scala:128)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Fokko** [comment] 2018-07-25 06:42
@vijayupadya Just to make sure. Is there only one Spark job is reading from the consumer group?

**Comment by vijayupadya** [comment] 2018-07-25 07:03
Yes, only one job is reading from a consumer group.

**Comment by sabeegrewal** [comment] 2018-07-25 20:37
This is fixed in #364

**Closed** 2018-07-25 22:01 UTC
Labels: known issue

**Comment by duboisej** [comment] 2018-11-13 16:02
I know this is closed, but I am experiencing this issue with the latest version, on Databricks: 

Version: azure-eventhubs-spark_2.11-2.3.6

Stack Trace: 


org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:224)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWrite$$anonfun$writeFiles$1$$anonfun$apply$3.apply(TransactionalWrite.scala:151)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWrite$$anonfun$writeFiles$1$$anonfun$apply$3.apply(TransactionalWrite.scala:145)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:89)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:175)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:84)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:126)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWrite$$anonfun$writeFiles$1.apply(TransactionalWrite.scala:145)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWrite$$anonfun$writeFiles$1.apply(TransactionalWrite.scala:102)
	at com.databricks.logging.UsageLogging$$anonfun$recordOperation$1.apply(UsageLogging.scala:313)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:188)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:183)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:13)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:221)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:13)
	at com.databricks.logging.UsageLogging$class.recordOperation(UsageLogging.scala:298)
	at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:13)
	at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:36)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:65)
	at com.databricks.spark.util.UsageLogger$class.recordOperation(UsageLogger.scala:54)
at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:44)
	at com.databricks.spark.util.UsageLogging$class.recordOperation(UsageLogger.scala:261)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.recordOperation(OptimisticTransaction.scala:59)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:79)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.recordDeltaOperation(OptimisticTransaction.scala:59)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWrite$class.writeFiles(TransactionalWrite.scala:102)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.writeFiles(OptimisticTransaction.scala:59)
	at com.databricks.sql.transaction.tahoe.sources.DeltaSink.addBatch(DeltaSink.scala:72)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:549)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:89)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:175)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:84)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:126)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:547)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:379)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:60)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:546)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:204)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:172)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:172)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:379)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:60)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:172)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:293)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:203)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4625.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4625.0 (TID 94161, 10.139.64.10, executor 8): java.lang.IllegalStateException: In partition 0 of 3psadeveventhub, with consumer group $Default, request seqNo 2367 is less than the received seqNo 2372. The earliest seqNo is 2371 and the last seqNo is 4414
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.checkCursor(CachedEventHubsReceiver.scala:115)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:130)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:179)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD.compute(EventHubsRDD.scala:122)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1747)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1735)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1734)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1734)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:962)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:962)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:962)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1970)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1918)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1906)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:759)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2141)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:194)
	... 47 more
Caused by: java.lang.IllegalStateException: In partition 0 of 3psadeveventhub, with consumer group $Default, request seqNo 2367 is less than the received seqNo 2372. The earliest seqNo is 2371 and the last seqNo is 4414
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.checkCursor(CachedEventHubsReceiver.scala:115)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:130)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:179)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD.compute(EventHubsRDD.scala:122)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Any update or other information I should be aware of?

**Comment by sabeegrewal** [comment] 2018-11-14 15:47
@duboisej - take a look at the message:
`request seqNo 2367 is less than the received seqNo 2372. The earliest seqNo is 2371 and the last seqNo is 4414`

How can you receive request seqNo `2367` when the earliest seqNo is `2371`? Take a look at the [FAQ](https://github.com/Azure/azure-event-hubs-spark/blob/master/FAQ.md).

**Comment by duboisej** [comment] 2018-11-14 16:45
@sabeegrewal  thanks! For some reason I never came across that FAQ in my research. Resolved the issue.

**Comment by davew-msft** [comment] 2020-07-10 18:11
I would ask that you consider re-opening this.  I can repro this quite reliably and others may too.  My use case is I unfortunately must start a stream and then union it to itself to duplicate the data, then union that again to itself.  Why?  To do some subsequent `flatMapGroupsWithState` where I need to figure out the sequence of events.  Regardless,

I can't explain this but I think somewhere when I'm unioning the df to itself the actual spark code is going BACK to the eh and requerying and somehow the offsets are getting confused during the requery.   

Here's why I think that...originally the **exact same code** was working when we were doing the exact same stream processing patterns (read the source, do some ETL, write to a sink), but we were using delta_source-to-delta_sink processing.  That performed horrendously so we rewrote it to be eh_source-to-eh_sink.  We do this pattern in literally hundreds of places with no issues even if we reprocess for offset -1 (the test case you mention in the FAQ).  We have never run into issues since switching to EH, throughput is great, couldn't be happier.  

Except this one stream where we do this goofy "union the stream to itself, thrice"...and I can't think of a better way to do it to get the logic we need.  And this is the only stream that throws this error.  I can assure you this is NOT due to the eh data getting aged as @sabeegrewal mentioned in the FAQ, please suspend disbelief and trust me on this one.   Sometimes we don't get this particular error, we get this error:  https://stackoverflow.com/questions/51441518/epoch-error-while-communicating-with-azure-event-hub .  "New receiver with higher epoch of '3109' is created hence current receiver with epoch '3108' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used."  Again, let me assure you that FOR THIS EVENT HUB WE HAVE 1 CONSUMER GROUP and this stream is the only consumer.  If I'm right and a requery is happening, some kind of race condition, the symptoms would definitely manifest as this being a second consumer on the cg.  Right?  

Here's one more reason why I think this error is some kind of race condition when we do stream-to-stream joins/unions...I can see that numInputRows is always 3x the number I set in maxEventsPerTrigger.  That seems extremely suspicious to me.  If I set maxEvents to 20000 I see numInputRows being 60K.  

One more reason...https://docs.databricks.com/spark/latest/structured-streaming/foreach.html ..."If you want to write the output of a streaming query to multiple locations, then you can simply write the output DataFrame/Dataset multiple times. However, each attempt to write can cause the output data to be recomputed (including possible re-reading of the input data). To avoid recomputations, you should cache the output DataFrame/Dataset, write it to multiple locations, and then uncache it. "  That seems suspicious.  If my unioning process is causing spark to go back and requery EH, then I can imagine the requery causing the epochs and offsets to get out of whack.  When we had all of this written as delta-to-delta streaming I was sourcing from one delta table and sinking to 5 others, in many of my streams.  When we rewrote everything to be eh-to-eh we started seeing the same errors (request seqNo does not match...).  I knew about the "possible re-reading of input data", looked at our prod code using delta-to-delta and could see from the IO that we were hitting that problem and didn't even know it!!! With my new eh-to-eh code I fixed that by simply adding more consumer groups and fiddling a bit with my readStreams and everything worked brilliantly.  

But this one is stumping me.  

I've gotten to the point of being able to repro this with a simple script.  I'm happy to provide.  

To the others experiencing this (@vijayupadya and @duboisej )...can you confirm if you saw the issues when doing a stream-to-stream join/union?  If so, I think we have a pattern worthy of investigation.
