### ISSUE TITLE
TimeoutException: Close operation on Receive Link (xxx) timed out

### ISSUE THREAD

**Issue by shi-ding** [Azure/azure-event-hubs-spark#480] opened 2020-03-24 13:20 UTC
We are using databricks running spark processes to read data from event hubs. It worked fine before but ever since Mar 17th, continuously see databricks job run failed with the below exceptions:

Caused by: java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver 'spark-38-60589' with higher epoch of '0' is created hence current receiver 'spark-38-61233' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:3d301a9800010d7f0049f19f5e7140ed_G13_B19, SystemTracker:xxxx:eventhub:eventhubdatabricks~12287xxxx, Timestamp:2020-03-17T21:28:18, errorContext[NS: xxxx.servicebus.windows.net, PATH: xxx/ConsumerGroups/databricks-raw-read/Partitions/11, REFERENCE_ID: LN_06a596_1584480493101_787_G13, PREFETCH_COUNT: 500, LINK_CREDIT: 500, PREFETCH_Q_LEN: 0]

Followed [doc](https://github.com/Azure/azure-event-hubs-spark/blob/master/FAQ.md) and confirmed there is only one job running in databricks and connect to one consumer group only. 

Found the [discussion ](https://github.com/Azure/azure-event-hubs-spark/issues/464) but do not see 2.3.14 available [here](https://github.com/Azure/azure-event-hubs-spark), so upgrade the latest available azure-eventhubs-spartk_2.11:2.3.13. 

Then started to see below exception continousely:

Caused by: com.microsoft.azure.eventhubs.TimeoutException: Close operation on Receive Link(LN_9de5aa_1584874433916_4bd_G37) timed out at 2020-03-22T11:05:41.955Z[Etc/UTC], errorContext[NS: xxxx.servicebus.windows.net, PATH: xxx/ConsumerGroups/databricks-raw-read/Partitions/2, REFERENCE_ID: LN_9de5aa_1584874433916_4bd_G37, PREFETCH_COUNT: 500, LINK_CREDIT: 473, PREFETCH_Q_LEN: 0

Could anyone shed some lights on this?

**Comment by nyaghma** [comment] 2020-03-24 16:41
@shi-ding Thanks for opening the issue. We should update the current version in the [README](https://github.com/Azure/azure-event-hubs-spark), but you can find the version 2.3.14 [here](https://search.maven.org/artifact/com.microsoft.azure/azure-eventhubs-spark_2.11/2.3.14.1/jar). Could you please try this version and let us know if you still face any error. Thanks.

**Comment by shi-ding** [comment] 2020-03-25 02:58
@nyaghma Thank you for your reply. Double confirmed and turns out already upgraded to 2.3.14.1 but exception persists. Could you help further on this?
![image](https://user-images.githubusercontent.com/57244064/77497068-5e4d8380-6e87-11ea-9301-1f1dd54cd82f.png)

**Comment by nyaghma** [comment] 2020-03-25 15:16
@shi-ding Thanks for confirming the version. The Timeout Exception is thrown by the underlying java client. One possible solution would be increasing the receiverTimeout/operationTimeout in the configuration (More info [here](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/spark-streaming-eventhubs-integration.md#eventhubsconf)). 
Could you please try this and let us know if that resolves the problem? If it doesn't, please give me more info about the task that you are doing so that I can repro the issue and investigate more.

**Comment by disciplined-coder** [comment] 2020-04-03 14:27
@nyaghma , Could you please explain a bit more in detail why the underlying java client throes timeout exception? The receiverTimeout/operationTimeout config parameters have default values of 60 seconds. But the job fails after 5 minutes (300 seconds) with the below error mentioned by @shi-ding . Could you please check? (Please note that these parameters were not modified in the job run; so the job should have failed after 60 seconds ideally, rather than failing after 300 seconds)

`Caused by: com.microsoft.azure.eventhubs.TimeoutException: Close operation on Receive Link(LN_9de5aa_1584874433916_4bd_G37) timed out at 2020-03-22T11:05:41.955Z[Etc/UTC], errorContext[NS: xxxx.servicebus.windows.net, PATH: xxx/ConsumerGroups/databricks-raw-read/Partitions/2, REFERENCE_ID: LN_9de5aa_1584874433916_4bd_G37, PREFETCH_COUNT: 500, LINK_CREDIT: 473, PREFETCH_Q_LEN: 0`

**Comment by nyaghma** [comment] 2020-04-06 20:59
The connector to the event hub service is using the OperationTimeout which has the default value of 300 seconds. That's why the job fails after 300 seconds and the connector doesn't retry the operation. This issue is being fixed in df4d8c663a2be72a71c06d34dd6e0d170b7ae34a by using the ReceiverTimeout which is 60 seconds by default.

**Closed** 2020-06-08 21:50 UTC
