### ISSUE TITLE
GetOffset returns old offset

### ISSUE THREAD

**Issue by xinxinzhan** [Azure/azure-event-hubs-spark#522] opened 2020-07-20 09:29 UTC
We are using **mapGroupsWithState** to process data from eventhub. We found that when "GroupStateTimeout.ProcessingTimeTimeout" is enabled & there is no new data in the source eventhub, everytime the streaming is restarted, all the batches (from the last staring offset of the source) will be processed again.

Below is our code snippet:

------------
val ehConf = EventHubsConf(connectionString)
  .setConsumerGroup("databricks")
  .setMaxEventsPerTrigger(1)
  .setStartingPosition(EventPosition.fromEndOfStream)

var streamingSelectDF= 
  spark.readStream
    .format("eventhubs")
    .options(ehConf.toMap)
    .load()
    .select()

val result = streamingSelectDF
  .as[InputRow]
  .groupByKey(_.key)
  .**mapGroupsWithState(GroupStateTimeout.ProcessingTimeTimeout)(updateAcrossEvents)**  // Enable Processing Timeout
  //.mapGroupsWithState(GroupStateTimeout.NoTimeout)(updateAcrossEvents)
  .toDF()
  .filter($"overbottleneck" === true)
  .select(
    to_json(struct($"key",$"squenceId",$"bottleneck",$"standard",$"EventTimestamp",$"compare",$"overbottleneck"))
      .alias("body"))
  .writeStream
  .format("eventhubs")
  .outputMode("update")
  .trigger(Trigger.ProcessingTime("0 second"))
  .options(eventHubsConfOutcome.toMap)
  .option("checkpointLocation", "/test/eventhubtest/test20")
  .start()

-------------

Note that here we specified to use GroupStateTimeout.ProcessingTimeTimeout. This issue only happens when timeout for the mapGroupsWithState is enabled. If we disable timeout (GroupStateTimeout.NoTimeout),there is no such issue.

When the above streaming is restarted (simulate job failure), from spark driver log we observed that GetOffset returned an old offset which is already processed:

--------------------
20/07/16 05:28:26 INFO EventHubsSource: GetOffset: ArrayBuffer(({"ehName":"xinzsourceeh","partitionId":0},328), ({"ehName":"xinzsourceeh","partitionId":1},291), ({"ehName":"xinzsourceeh","partitionId":2},310), ({"ehName":"xinzsourceeh","partitionId":3},321))

--------------------

Then, getBatch was called with end offset earlier then start offset, which result to below warnings and the re-processing of all the data. 

--------------------
20/07/16 05:28:26 INFO EventHubsSource: getBatch called with start = Some({"xinzsourceeh":{**"2":319,"1":300,"3":330,"0":337**}}) and end = {"xinzsourceeh":{**"2":310,"1":291,"3":321,"0":328**}}

20/07/16 05:28:26 WARN EventHubsSource: Partition {"ehName":"xinzsourceeh","partitionId":0}'s sequence number was changed from 337 to 328, some data may have been missed. 
Some data may have been lost because they are not available in EventHubs any more; either the
 data was aged out by EventHubs or the EventHubs instance may have been deleted before all the data in the
 instance was processed.
    
20/07/16 05:28:26 WARN EventHubsSource: Partition {"ehName":"xinzsourceeh","partitionId":1}'s sequence number was changed from 300 to 291, some data may have been missed. 
Some data may have been lost because they are not available in EventHubs any more; either the
 data was aged out by EventHubs or the EventHubs instance may have been deleted before all the data in the
 instance was processed.
    
20/07/16 05:28:26 WARN EventHubsSource: Partition {"ehName":"xinzsourceeh","partitionId":2}'s sequence number was changed from 319 to 310, some data may have been missed. 
Some data may have been lost because they are not available in EventHubs any more; either the
 data was aged out by EventHubs or the EventHubs instance may have been deleted before all the data in the
 instance was processed.
    
20/07/16 05:28:26 WARN EventHubsSource: Partition {"ehName":"xinzsourceeh","partitionId":3}'s sequence number was changed from 330 to 321, some data may have been missed. 
Some data may have been lost because they are not available in EventHubs any more; either the
 data was aged out by EventHubs or the EventHubs instance may have been deleted before all the data in the
 instance was processed.

--------------------

I am wondering in which case can `getOffset()` return an old offset.

**Comment by nyaghma** [comment] 2020-07-30 03:03
@xinxinzhan I've been investigating this issue and the problem is not what getOffset() returns. In short, this issue happens because the recovery is not going through the expected path due to the fact that Spark is checkpointing batches of size 0 under the scenario you described. These checkpoints of size 0 cause the issue during the recovery which results in reading events from the beginning of the stream.

In order to avoid this situation in your setting, you can disable the "spark.sql.streaming.noDataMicroBatches.enabled" in the  SparkSession config. I was able to resolve the issue by using the below configuration. 

import org.apache.spark.sql.SparkSession
val spark = SparkSession
  .builder
  .config("spark.sql.streaming.noDataMicroBatches.enabled", false)
  .getOrCreate

**Comment by xinxinzhan** [comment] 2020-07-30 04:25
Hi @nyaghma , thanks a lot for the suggestion! It works fine and resolved our issue. Really appreciate your help!

**Comment by xinxinzhan** [comment] 2020-08-12 01:55
Sorry to reopen this thread as I found another issue after adding "spark.sql.streaming.noDataMicroBatches.enabled". 

We found that after above parameter is set to false, the ProcessingTimeTimeout never happens for the first group (the first data that comes in the first batch). For the second and subsequent groups, timeout can happen as expected. 

Do you have any idea about this?

**Comment by nyaghma** [comment] 2021-06-24 20:36
I think this is related to the fact that the first batch during recovery could be a re-execution of the latest batch in the previous job if it's hasn't been committed. 
More information on ProcessingTimeTimeout guarantees can be found [here](https://spark.apache.org/docs/2.3.1/api/java/org/apache/spark/sql/streaming/GroupState.html).

**Closed** 2021-06-24 20:43 UTC
