### ISSUE TITLE
org.apache.qpid:proton-j warning at compilation in scala

### ISSUE THREAD

**Issue by DenisBiondic** [Azure/azure-event-hubs-spark#432] opened 2019-02-07 12:40 UTC
Bug Report:

- Actual behavior
Following warning is shown when referencing libraryDependencies += "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.9"

[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * org.apache.qpid:proton-j:0.31.0 is selected over 0.26.0
[warn]      +- com.microsoft.azure:azure-eventhubs:2.2.0          (depends on 0.31.0)
[warn]      +- com.microsoft.azure:qpid-proton-j-extensions:1.1.0 (depends on 0.26.0)

- Expected behavior

no warning 

- Spark version

probably irrelevant, but here is the relevant build.sbt part:

libraryDependencies += "args4j" % "args4j" % "2.33"

libraryDependencies += "com.databricks" %% "spark-avro" % "4.0.0"
libraryDependencies += "com.databricks" %% "spark-csv" % "1.5.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.2" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-sql" %  "2.3.2" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-hive" % "2.3.2" % "provided"
libraryDependencies += "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.9"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.5"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.5" % "test"

**Comment by sjkwak** [comment] 2019-02-08 17:07
Hi @DenisBiondic, thanks for reporting the issue. We will update qpid-proton-j-extensions package to address the warning.

**Comment by sjkwak** [comment] 2019-04-09 00:12
The issue is resolved by #437.

**Closed by sjkwak** 2019-04-09 00:12 UTC
