### ISSUE TITLE
ReceiverDisconnectedException executors keep retrying 

### ISSUE THREAD

**Issue by belgacea** [Azure/azure-event-hubs-spark#464] opened 2019-10-11 11:54 UTC
Hello @sjkwak I am trying to consume events from eventhubs and I am continuously getting the following exceptions .
Like @sakthig described in #388, the driver does not quit and the executors retry forever. Yet I can see outgoing messages in Azure portal but no messages in the database (I'm using the [spark-cassandra-connector](https://github.com/datastax/spark-cassandra-connector) along with a `ForeachWriter` to insert events in Cassandra.).
I have already read the [docs](https://github.com/Azure/azure-event-hubs-spark/blob/master/FAQ.md), but consuming with the `default` consumer (without any other job running at the same time) or with a freshly created one (same as @sakthig in #371 ) still gives me the same issue...

```
19/10/11 12:52:43 WARN MessageReceiver: clientId[PR_32d713_1570791153397_MF_ffd652_1570791044878-InternalReceiver], receiverPath[dummysender/ConsumerGroups/spark_test/Partitions/0], linkName[LN_0cf9d9_1570791153443_c68_G39], onError: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f29772d8000332ae0098d2405da05ef1_G39_B10, SystemTracker:eventhubs-loadtesting:eventhub:dummysender~16383|spark_test, Timestamp:2019-10-11T10:52:43
19/10/11 12:52:43 WARN MessageReceiver: clientId[PR_2ecef9_1570791153474_MF_ffd652_1570791044878-InternalReceiver], receiverPath[dummysender/ConsumerGroups/spark_test/Partitions/0], linkName[LN_504241_1570791153563_c68_G39], onError: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f29772d8000332ae0098d2455da05ef6_G39_B10, SystemTracker:eventhubs-loadtesting:eventhub:dummysender~16383|spark_test, Timestamp:2019-10-11T10:52:43
19/10/11 12:52:44 WARN MessageReceiver: clientId[PR_549cde_1570791158911_MF_ffd652_1570791044878-InternalReceiver], receiverPath[dummysender/ConsumerGroups/spark_test/Partitions/0], linkName[LN_814630_1570791158935_c68_G39], onError: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f29772d8000332ae0098d26e5da05ef6_G39_B10, SystemTracker:eventhubs-loadtesting:eventhub:dummysender~16383|spark_test, Timestamp:2019-10-11T10:52:44
19/10/11 12:52:49 WARN MessageReceiver: clientId[PR_436027_1570791158962_MF_ffd652_1570791044878-InternalReceiver], receiverPath[dummysender/ConsumerGroups/spark_test/Partitions/0], linkName[LN_f2d417_1570791159052_c68_G39], onError: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f29772d8000332ae0098d2705da05ef7_G39_B10, SystemTracker:eventhubs-loadtesting:eventhub:dummysender~16383|spark_test, Timestamp:2019-10-11T10:52:49
19/10/11 12:52:49 WARN MessageReceiver: clientId[PR_f377a2_1570791159525_MF_ffd652_1570791044878-InternalReceiver], receiverPath[dummysender/ConsumerGroups/spark_test/Partitions/0], linkName[LN_716d3c_1570791159549_c68_G39], onError: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f29772d8000332ae0098d2795da05efc_G39_B10, SystemTracker:eventhubs-loadtesting:eventhub:dummysender~16383|spark_test, Timestamp:2019-10-11T10:52:49
19/10/11 12:52:50 WARN MessageReceiver: clientId[PR_430534_1570791164548_MF_ffd652_1570791044878-InternalReceiver], receiverPath[dummysender/ConsumerGroups/spark_test/Partitions/0], linkName[LN_e19564_1570791164638_c68_G39], onError: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f29772d8000332ae0098d2a95da05efc_G39_B10, SystemTracker:eventhubs-loadtesting:eventhub:dummysender~16383|spark_test, Timestamp:2019-10-11T10:52:50
```

Spark = `2.4.0`
Dependencies : 

```
com.test:spark-test_2.11:0.7.3 [S]
  +-com.datastax.spark:spark-cassandra-connector_2.11:2.4.1 [S]
  | +-com.twitter:jsr166e:1.1.0
  | +-commons-beanutils:commons-beanutils:1.9.3
  | | +-commons-collections:commons-collections:3.2.2
  | |
  | +-io.netty:netty-all:4.0.33.Final
  | +-joda-time:joda-time:2.3
  | +-org.joda:joda-convert:1.2
  | +-org.scala-lang:scala-reflect:2.11.11 [S]
  |
  +-com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.13
  | +-com.microsoft.azure:azure-eventhubs:2.3.2
  | | +-com.microsoft.azure:qpid-proton-j-extensions:1.2.0
  | | | +-org.apache.qpid:proton-j:0.31.0
  | | |
  | | +-org.apache.qpid:proton-j:0.31.0
  | | +-org.slf4j:slf4j-api:1.7.25
  | |
  | +-org.scala-lang.modules:scala-java8-compat_2.11:0.9.0 [S]
  |
  +-com.microsoft.azure:azure-eventhubs:2.3.2
  | +-com.microsoft.azure:qpid-proton-j-extensions:1.2.0
  | | +-org.apache.qpid:proton-j:0.31.0
  | |
  | +-org.apache.qpid:proton-j:0.31.0
  | +-org.slf4j:slf4j-api:1.7.25
  |
  +-com.twitter:jsr166e:1.1.0
  +-commons-configuration:commons-configuration:1.10
  | +-commons-lang:commons-lang:2.6
  | +-commons-logging:commons-logging:1.1.1
  |
  +-io.spray:spray-json_2.12:1.3.5 [S]
  +-org.apache.logging.log4j:log4j-core:2.11.1
  +-org.scala-lang.modules:scala-java8-compat_2.11:0.9.0 [S]
```

**Comment by agilityhawk** [comment] 2020-01-16 12:48
Same error. Started occurring more frequently this week. 
Using Databricks Runtime 6.1.
Notebook Language: Python
Eventhub Partitions: 4
Databricks workers: 2-4 (autoscaling)

Here is the stack trace.
`at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:104)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.drainPendingReceives(MessageReceiver.java:466)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:451)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:746)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:106)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:512)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver 'spark-10-8438' with higher epoch of '0' is created hence current receiver 'spark-10-8437' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ae2d937e00011231000039605e2057f2_G1S2_B0S3, SystemTracker:xxxx-eh-namespace:eventhub:xxxx-eh~24575|databricks-consumer, Timestamp:2020-01-16T12:32:55, errorContext[NS: xxxx-eh-namespace.servicebus.windows.net, PATH: xxxx-eh/ConsumerGroups/databricks-consumer/Partitions/2, REFERENCE_ID: LN_f04bc1_1579177970608_3a_G1S2, PREFETCH_COUNT: 500, LINK_CREDIT: 500, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:745)
	... 15 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2360)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2348)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2347)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2347)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1101)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1101)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1101)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2579)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2527)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2515)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:896)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2280)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:270)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:280)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:80)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:86)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:508)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollectResult(limit.scala:55)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectResult(Dataset.scala:2889)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3501)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2856)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2856)
	at org.apache.spark.sql.Dataset$$anonfun$54.apply(Dataset.scala:3485)
	at org.apache.spark.sql.Dataset$$anonfun$54.apply(Dataset.scala:3480)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:240)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:97)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:170)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withAction(Dataset.scala:3480)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2856)
	at org.apache.spark.sql.execution.streaming.MemorySink.addBatch(memory.scala:280)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:568)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:240)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:97)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:170)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:566)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:263)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:565)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:207)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:175)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:175)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:263)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:175)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:169)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:296)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:208)
Caused by: java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver 'spark-10-8438' with higher epoch of '0' is created hence current receiver 'spark-10-8437' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ae2d937e00011231000039605e2057f2_G1S2_B0S3, SystemTracker:xxxxh-namespace:eventhub:xxxx-eh~24575|databricks-consumer, Timestamp:2020-01-16T12:32:55, errorContext[NS: xxxx-eh-namespace.servicebus.windows.net, PATH: xxxx-eh/ConsumerGroups/databricks-consumer/Partitions/2, REFERENCE_ID: LN_f04bc1_1579177970608_3a_G1S2, PREFETCH_COUNT: 500, LINK_CREDIT: 500, PREFETCH_Q_LEN: 0]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:104)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.drainPendingReceives(MessageReceiver.java:466)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:451)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:746)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:106)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:512)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver 'spark-10-8438' with higher epoch of '0' is created hence current receiver 'spark-10-8437' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ae2d937e00011231000039605e2057f2_G1S2_B0S3, SystemTracker:xxxx-eh-namespace:eventhub:xxxx-eh~24575|databricks-consumer, Timestamp:2020-01-16T12:32:55, errorContext[NS: xxxx-eh-namespace.servicebus.windows.net, PATH: xxxx-eh/ConsumerGroups/databricks-consumer/Partitions/2, REFERENCE_ID: LN_f04bc1_1579177970608_3a_G1S2, PREFETCH_COUNT: 500, LINK_CREDIT: 500, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:745)
	... 15 more
OK`

**Comment by nyaghma** [comment] 2020-03-18 15:56
Could you please upgrade the eventhubs-spark connector to the current version (2.3.14.1) and let us know if you see the error again.

**Comment by nyaghma** [comment] 2020-03-23 14:26
I'm closing this issue now. Please reopen if you see the same problem using the current version.

**Closed by nyaghma** 2020-03-23 14:26 UTC

**Comment by Kanwaldeep** [comment] 2020-08-13 20:43
I am having this exact problem using the latest version of the connector 2.3.17. There is only a single spark streaming application running reading data from EventHub.
